#!/bin/bash

IP=10.23.20.10
SPACE=1
PRESET=4
ACTION="activate" # or deactivate

DIR=${0%/*}
NAME=${0##*/}

log() { echo "$(date) [${NAME}]  $@" >> ${DIR}/lights.log; }

log "${ACTION} preset ${PRESET} in space ${SPACE}"
${DIR}/lights/preset $IP $SPACE $PRESET $ACTION

ret=$?
[ $ret -eq 0 ] && log "success" || log "failed ($ret)" 
exit $ret

