#!/bin/bash

VOLUME=0
FADETIME=5

DIR=${0%/*}
NAME=${0##*/}
log() { echo "$(date) [${NAME}]  $@" >> ${DIR}/spotify.log; }



log "fading volume to ${VOLUME} over ${FADETIME} seconds"
${DIR}/spotify/vol fd ${VOLUME} ${FADETIME}

log "pausing"
${DIR}/spotify/pause

log 'complete'

