#!/bin/bash

PLAYLIST="spotify:playlist:0JN69ahQbHMNyElBYj57Hz" # Redeemer City Church
VOLUME=100
FADETIME=2
SHUFFLE=true
REPEAT=true

DIR=${0%/*}
NAME=${0##*/}
log() { echo "$(date) [${NAME}]  $@" >> ${DIR}/spotify.log; }

log 'launching spotify'
${DIR}/spotify/launch

log "setting volume=0 repeat=${REPEAT} shuffle=${SHUFFLE}"
${DIR}/spotify/vol 0
${DIR}/spotify/repeat ${REPEAT}
${DIR}/spotify/shuffle ${SHUFFLE}

log "playing ${PLAYLIST}"
${DIR}/spotify/play "${PLAYLIST}"
log "skip ahead to 5 secs"
${DIR}/spotify/position 5

log "fading volume to ${VOLUME} over ${FADETIME} seconds"
${DIR}/spotify/vol fd ${VOLUME} ${FADETIME} 

log 'complete'

