#!/bin/bash

IP="${1:-10.23.20.10}"
SPACE="${2:-1}"
PRESET="${3:-1}"
ACTION="${4:-activate}"

DATA="<setlevels><presetaction preset=\"${PRESET}\" space=\"${SPACE}\" action=\"${ACTION}\"/></setlevels>"

curl -sm 3 -H "Content-Type: text/plain" -d "${DATA}" http://${IP}/action.cgi

ret=$?
[ $ret -eq 52 ] && { exit 0; } || { exit $ret; }

