#!/bin/bash

IP="${1:-10.23.20.10}"

DATA="<setlevels><release_all space=\"0\"/></setlevels>"

curl -sm 3 -H "Content-Type: text/plain" -d "${DATA}" http://${IP}/action.cgi

ret=$?
[ $ret -eq 52 ] && { exit 0; } || { exit $ret; }

