#!/usr/bin/env osascript

# Set spotify playhead position to x seconds (0 - track length) with negative values counting backwards from the end of the track

# run is a special name that is called when the applescript loads and is passed any arguments (argv) from the 
# commandline if not opened like an app
on run argv
	set targetSecs to 3
	
	if (count of argv) >= 1 then
		set targetSecs to item 1 of argv
	end if
	delay (0.1)

	tell application "Spotify"
		set currentTrackLength to duration of current track / 1000
    
    if (targetSecs as number) < 0 then
      set targetSecs to (currentTrackLength as number) + (targetSecs as number)
      
      if (targetSecs as number) < 0 then
        set player position to 0
      else
        set player position to targetSecs
      end if
		else if (targetSecs as number) > (currentTrackLength as number) then
			set player position to currentTrackLength
		else
			set player position to targetSecs
		end if
	end tell
end run
